AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Shreya Enterprises Ecommerce App

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09c8d8b4175992e90 # Amazon Linux 2 AMI in ap-south-1
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyPair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user
          chkconfig docker on
          curl -sSL https://get.docker.com/ | sh
          docker run -d -p 80:5000 vijaykumara/shreya-ecommerce:latest
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
Parameters:
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair
Outputs:
  SiteURL:
    Description: URL of the ecommerce app
    Value: !Sub "http://${EC2Instance.PublicDnsName}"
